version: '3.1'

services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    env_file:
      - .env.docker-dev

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env.docker-dev
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env.docker-dev
